version: "2"
plugins:
  tslint:
    enabled: true
  config:
    config: tsconfig.json
    extensions:
    - .js
    - .ts
ratings:
  paths:
    - "src/**/*.ts"

exclude_patterns:
  - "src/**/*.spec.ts"
  - "node_modules/"
  - "**/node_modules/"

